define({
  root: ({
    _widgetLabel: "Not used",
    label1: "Click/tap map to identify items.",
    label2: "Items within the appropriate scale range will appear in this popup regardless if they are turned on in the legend. If the desired items are not appearing in the popup, try zooming in first.",
    label3: "Additional identify details are available by selecting 'Enable Pop-up' option for each layer in the Layer List.",
    tab1label: "General",
    tab2label: "Green",
    tab3label: "Sewer",
    tab4label: "LandUse",
    tab5label: "Region",
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 1
});
